import { sha256Hex } from "./hash.ts";
import { stableStringify } from "./json-stable.ts";

export interface BlockManifestData {
  id: string;
  version: string;
  summary: string;
  produces: string[];
}

export interface CapturedFile {
  path: string;
  content: Uint8Array;
}

interface EmbeddedPayload {
  files: Record<string, string>; // relPath -> base64 content
  hashes: Record<string, string>; // relPath -> sha256 hex of content
}

/** Build the manifest object a generated block prints for `--manifest`. */
export function buildManifestObject(
  manifest: BlockManifestData,
  sortedPaths: string[],
) {
  return {
    id: manifest.id,
    version: manifest.version,
    summary: manifest.summary,
    params: {} as Record<string, never>,
    produces: sortedPaths,
    needs: [] as string[],
  };
}

/**
 * Generate the source of a self-contained, Bun-executable `.block.ts` file.
 *
 * The block embeds its files as a base64 JSON payload and implements the
 * universal block contract (`--manifest`, `--apply`, `--test`) with no imports
 * from bspec — it must run standalone via `bun <file>.block.ts <flag>`.
 */
export function generateBlockSource(
  manifest: BlockManifestData,
  files: CapturedFile[],
): string {
  const sorted = [...files].sort((a, b) => a.path.localeCompare(b.path));
  const payload: EmbeddedPayload = { files: {}, hashes: {} };
  for (const f of sorted) {
    payload.files[f.path] = Buffer.from(f.content).toString("base64");
    payload.hashes[f.path] = sha256Hex(f.content);
  }

  const manifestJson = buildManifestObject(
    manifest,
    sorted.map((f) => f.path),
  );

  const payloadB64 = Buffer.from(stableStringify(payload), "utf8").toString("base64");
  const manifestLiteral = JSON.stringify(manifestJson, null, 2);

  return `#!/usr/bin/env bun
// Generated by bspec. Self-contained folder-snapshot block. Do not edit.
import { createHash } from "node:crypto";
import { mkdir, writeFile, readFile, mkdtemp, rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";

const MANIFEST = ${manifestLiteral} as const;

const PAYLOAD = JSON.parse(
  Buffer.from(${JSON.stringify(payloadB64)}, "base64").toString("utf8"),
) as { files: Record<string, string>; hashes: Record<string, string> };

function sha256Hex(data: Uint8Array): string {
  return createHash("sha256").update(data).digest("hex");
}

async function applyTo(outDir: string): Promise<void> {
  for (const relPath of Object.keys(PAYLOAD.files).sort()) {
    const dest = join(outDir, relPath);
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, Buffer.from(PAYLOAD.files[relPath], "base64"));
  }
}

async function selfTest(): Promise<void> {
  const dir = await mkdtemp(join(tmpdir(), "bspec-block-test-"));
  try {
    await applyTo(dir);
    for (const relPath of MANIFEST.produces) {
      const expected = PAYLOAD.hashes[relPath];
      let actual: string;
      try {
        actual = sha256Hex(await readFile(join(dir, relPath)));
      } catch {
        throw new Error("Missing produced file after apply: " + relPath);
      }
      if (actual !== expected) {
        throw new Error("Hash mismatch for " + relPath);
      }
    }
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

async function main(): Promise<void> {
  const [flag, ...rest] = process.argv.slice(2);
  if (flag === "--manifest") {
    process.stdout.write(JSON.stringify(MANIFEST, null, 2) + "\\n");
    return;
  }
  if (flag === "--apply") {
    const outDir = rest[0];
    if (!outDir) {
      process.stderr.write("Usage: <block> --apply <out_dir> <params.json>\\n");
      process.exit(2);
    }
    await applyTo(outDir);
    return;
  }
  if (flag === "--test") {
    try {
      await selfTest();
      process.stdout.write("ok\\n");
    } catch (err) {
      process.stderr.write("FAIL: " + (err as Error).message + "\\n");
      process.exit(1);
    }
    return;
  }
  process.stderr.write("Unknown command. Use --manifest, --apply, or --test.\\n");
  process.exit(2);
}

main().catch((err) => {
  process.stderr.write(String((err as Error)?.stack ?? err) + "\\n");
  process.exit(1);
});
`;
}
